### PR TITLE
fix: history of multiple chats, ui improvements

### LINKED ISSUE #6: Different chats show same messages
# Description

When having 2 chats with different recipients, same messages are shown in both chats:

Image
Image

### PR DESCRIPTION
**Pull request by igor-sirotin**
Fixes https://github.com/logos-co/logos-chatsdk-ui/issues/6

# Description

- Auto-initialize and auto-start chat on launch; keep chat menu state synced.
- Fix false "Failed to create conversation" popup by accepting `returnCode == 0`.
- Store messages per conversation and render them on selection.
- Prompt for a custom initial message when creating a new conversation.
- Add identity display in the status bar (my ID + peer ID snippets) and fix label sizing/updates.
- Add thread-safety around conversation/message maps.
- Make `onChatsdkNewConversation` the single source of truth for creating conversations, eliminating duplicate entries.
- Work around missing conversation IDs from `newPrivateConversationResult` by storing the pending initial message and injecting it into the first newly created conversation (issue #86).
- Add unread counters in the conversation list (red circular badge, capped at 99+), increment on new messages, clear on selection, and show unread for newly created conversations when nothing is selected.

## Notes
- The initial-message workaround relies on the next `newConversation` event corresponding to the initiated private conversation.
- Linked issue: https://github.com/logos-messaging/logos-chat/issues/86

### CODE REVIEW

File: src/ChatSDKWindow.h [hunk 1]
```diff
@@ -67,12 +73,22 @@ private slots:
...
+    struct MessageInfo {
+        QString sender;
+        QString content;
+        QDateTime timestamp;
+        bool isMe;
+    };
     QMap<QString, ConversationInfo> m_conversations;
+    QMap<QString, QList<MessageInfo>> m_messages;
     QString m_currentConversationId;  // Currently selected conversation
+    QMutex m_conversationsMutex;  // Protect conversation and message maps from concurrent access
```
Comment (plopezlpz) [inline src/ChatSDKWindow.h:93]: not needed: all map access occurs on the main thread via Qt::QueuedConnection

**Review by plopezlpz — APPROVED** [review]
